### ISSUE TITLE
link dead - update?

### ISSUE THREAD

**Issue by loneicewolf** [Mysterie/uncompyle2#35]
this [link](https://www.csr.uvic.ca/~aycock/python/) is dead (at least for me) - is there any update?

**Comment by loneicewolf** [comment]
![image](https://github.com/Mysterie/uncompyle2/assets/68499986/cbc44a5f-ad23-45d3-aa75-f1a2747033e2)

**Comment by caot** [comment]
It can be found @ https://legacy.python.org/workshops/1998-11/proceedings/papers/aycock-little/aycock-little.html

The author moved to https://pages.cpsc.ucalgary.ca/~aycock/

**Comment by rocky** [comment]
And if you are talking about the grammar system, see http://pages.cpsc.ucalgary.ca/~aycock/spark/ lists http://pages.cpsc.ucalgary.ca/~aycock/spark/spark-0.7.pre-alpha-7.py and http://pages.cpsc.ucalgary.ca/~aycock/spark/spark-0.6.1.tar.gz 

But you can install this from PyPI: https://pypi.org/project/spark-parser/

**Comment by loneicewolf** [comment]
Thanks to both of you!
